### ISSUE TITLE
stages with 'skipped due to earlier failure(s)' should have attribute or another status

### ISSUE THREAD

**Issue by ipleten** [jenkinsci/opentelemetry-plugin#281]
### What feature do you want to see added?

Hello,
We are trying to use opentelemetry  to find where exactly pipelines is failed and build some alerting on this.
Currently if stage fails all other also marked as failed. So using search  with otel_status='ERROR' will return all stages - the one which actually failed and all  next which were marked  as 'skipped due to earlier failure(s)'. Which is a hard to detect which one is really failed. They also have the same exception.

I'm not quite sure if it's our pipeline specific as we are using Jenkins MPL  or it's how this plugin works.

Here is an example in there pipeline failed earlier and what I see in tracing.
![image](https://user-images.githubusercontent.com/6207156/147769666-2c2b365c-2dbb-442c-9dcd-8a784b45ff9e.png)

**Comment by cyrille-leclerc** [comment]
Good catch, thanks.
We were also working on this family of UX glitches with @v1v and @kuisathaverat . We have already created:
* https://github.com/jenkinsci/opentelemetry-plugin/issues/262
* https://github.com/jenkinsci/opentelemetry-plugin/pull/263

We need to continue to improve the UX for this scenario.
We have to improve `MonitoringPipelineListener#endCurrentSpan` to handle differently `AbortException`.

Code: https://github.com/jenkinsci/opentelemetry-plugin/blob/opentelemetry-1.1.0-arc2/src/main/java/io/jenkins/plugins/opentelemetry/job/MonitoringPipelineListener.java#L287-L294

Span.statusCode should be set to `UNSET` rather than `KO` with a status string that look like `STEP_ABORTED`

**Comment by cyrille-leclerc** [comment]
@ipleten can you look at the UX of https://github.com/jenkinsci/opentelemetry-plugin/pull/283 ? Does it improve the readability?

**Comment by cyrille-leclerc** [comment]
@ipleten can you please test https://github.com/jenkinsci/opentelemetry-plugin/releases/tag/opentelemetry-1.2.0-rc1 ?
