### ISSUE TITLE
Add support for Jenkins server logging in JSON format

### ISSUE THREAD

**Issue by NickWemekamp** [jenkinsci/opentelemetry-plugin#458]
### What feature do you want to see added?

Hi,

I think a nice addition to this plugin would be to add support for the Jenkins server to log in JSON format to a file and/or to the console.

One possibility would be to add a dependency to https://github.com/elastic/ecs-logging-java and add an example logging.properties to the README that documents how to use this formatter like https://support.cloudbees.com/hc/en-us/articles/115002626172-Configure-Loggers-for-Jenkins (under solution 2) but then like this:
```
.level = INFO
handlers= java.util.logging.ConsoleHandler

java.util.logging.ConsoleHandler.level=INFO
java.util.logging.ConsoleHandler.formatter=co.elastic.logging.jul.EcsFormatter
```

I am not sure if you think this plugin is the right place for this functionality. The benefits would be that with JSON logging it's easier to parse logs for a logging backend which is semi-related to telemetry. But JSON logging is also a feature that would fit in the core Jenkins project.

**Comment by cyrille-leclerc** [comment]
Thanks @NickWemekamp .
Would the solution of having Jenkins system logs being sent to the OpenTelemetry backend, the same way we sent the pipeline logs, work for you?

The solution you propose to adopt the Elastic ECS format for Jenkins logs is not a perfect match for the Jenkins OpenTelemetry Plugin as our focus is to export Jenkins observability signals (metrics, job execution details as traces, and logs) to OpenTelemetry backends and so to ship Jenkins logs using OpenTelemetry logs.
Does it make sense to you?

**Comment by NickWemekamp** [comment]
Yes that would work. I think your solution is easier to use as well. 

Will you be adding more https://javadoc.io/static/io.opentelemetry/opentelemetry-api-trace/0.13.1/io/opentelemetry/api/trace/attributes/SemanticAttributes.html fields? the Exception related fields are useful.

**Comment by cyrille-leclerc** [comment]
PErfect Nick, the plan is indeed to add all the Semantic Attributes to get parity with https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/v1.14.0/instrumentation/java-util-logging/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/jul/JavaUtilLoggingHelper.java

**Comment by cyrille-leclerc** [comment]
Problem solved adding the capability to export Jenkins server logs through OpenTelemetry.

Can you please test https://github.com/jenkinsci/opentelemetry-plugin/releases/tag/opentelemetry-2.8.0-rc1

**Comment by cyrille-leclerc** [comment]
Thanks @NickWemekamp for testing.

Good catch, the UX should be improved.

> Is it also possible to only send the logging from the Jenkins server process and not the pipeline/job logs? Maybe that can be added as an option as well.

Valid point. 
❓  Can you confirm if you are interested in sending both the Jenkins server logs and the pipeline logs to the OpenTelemetry backend? Or if you just want to send the Jenkins serv do you want to do so?
❓ By the way, what's your OpenTelemetry backend? Have you been using the storage of pipeline logs in the Otel backend? 

> And the logs are sent through the OTEL endpoint right? Because under the store pipeline logs tech preview I have to configure an elasticsearch backend which is a bit confusing.

Yes logs are sent to the Otel endpoint.

You had to provide the Elasticsearch config because you chose the option _"Store pipeline logs In Elastic and visualize logs both in Elastic and through Jenkins"_. 
You would not have been asked to provide the Elasticsearch config if you had chosen the option _"Store pipeline logs In Elastic and visualize logs exclusively in Elastic (logs no longer visible through Jenkins screens)"_.


I may not have the bandwidth to improve the UX soon. 
❓ Are you interested in a GA version with setup guided by documentation relying on the not great UX or do you prefer to wait for the polished UX?

**Comment by NickWemekamp** [comment]
I'm only interested in sending the Jenkins server logs. Because otherwise I have to configure the authorization on my Elasticsearch instance as well for the Jenkins logs. And the logs page is good enough for our usecase and CTRL+F also works.
OpenTelemetry backend is Elasticsearch with an APM server. I don't store the pipeline logs.

I prefer to wait. The reason for this is that we are using Elastic a 7.X release currently so I can't use this feature until our cluster is running on version 8 (for the OTEL Logs compatibility in the APM server). And because I can only send both logs right now and some jobs produce lots of logging (5+MB per job run). 

It still is a nice addition the plugin right now, having the option to alert on Jenkins errors/warnings and search for them is handy.
