### ISSUE TITLE
Set `OTEL_SERVICE_NAME` as part of the exported environment variables

### ISSUE THREAD

**Issue by evgeni** [jenkinsci/opentelemetry-plugin#465]
### What feature do you want to see added?

In https://github.com/jenkinsci/opentelemetry-plugin/blob/7b7da3489bdc40163b32ba7241b7eb31362e64a8/src/main/java/io/jenkins/plugins/opentelemetry/JenkinsOpenTelemetryPluginConfiguration.java#L362-L383 you set a few env variables that are useful for processes running *inside* Jenkins (via `sh` and friends) to report telemetry data.

I would like to see `OTEL_SERVICE_NAME` (as returned by `getServiceName()`) be present there too, so that the reporting happens into the right service name (and not some default the launched process might have).

**Comment by v1v** [comment]
Hello @evgeni ,

As far as I see splitting service name is a good practice, let me explain my thoughts with the below example:

Given a Jenkins pipeline that runs `Maven` and `Ansible`, if all those integrations are instrumented with OpenTelemetry, then I'd expect a service for each one.
 
```
Jenkins Pipeline trace
    Maven build trace
        Ansible trace
```

By doing so, there is a separation between traces by the service, and the context propagation can help with presenting all those traces together. So from the Jenkins trace you will be able to see all the specific spans for each pipeline step and the other traces  for the Maven and Ansible executions.

The below screenshots can help with how the visualisation works with the context propagation by using a subset of the above services (maven and jenkins):
- In [Jaeger](https://github.com/jenkinsci/opentelemetry-plugin/blob/master/docs/images/jenkins-maven-execution-trace-jaeger.png)
- In [Elastic](https://github.com/jenkinsci/opentelemetry-plugin/blob/master/docs/images/jenkins-maven-execution-trace-elastic.png) 

Can you please elaborate your use case?

Thanks

**Comment by evgeni** [comment]
I might have been (or am :sweat_smile: ) holding it wrong ;)

I'm reporting against honeycomb.io and somehow the trace view led me to believe I can only ever see one *service*. But that's not correct, I can very well see what you describe in the screenshots after selecting the right trace:

![image](https://user-images.githubusercontent.com/94284/176212342-9331fab0-06b4-4f67-91f3-57888e7b6b07.png)

So yeah, I guess it's OK the way it is :)

**Comment by v1v** [comment]
Thanks for the update.

For the record, we initially attempted to use the `OTEL_SERVICE_NAME` (as part of one of our Jenkins Shared Library, since the Jenkins OpenTelemetry Plugin version we used at that time didn't have support for the environment variables.) In any case, we removed the support (see https://github.com/elastic/apm-pipeline-library/pull/1261) as it didn't work quite well with the Elastic specific Observability solution, for instance, it could no infer the Service version correctly as two different versions were coming from different data but using the same Service name.

Using different services per integration and context propagation can help with identifying when a version has been upgraded in a particular service, if the OpenTelemetry vendor provides that capability
