### ISSUE TITLE
sending jenkins metrics from otel plugin to elastic APm

### ISSUE THREAD

**Issue by Neelam-zanvar** [jenkinsci/opentelemetry-plugin#525]
How can i configure otel plugin to send job metric to elastic APM via otel collector. what will be the otel collector receiver>

**Comment by v1v** [comment]
https://github.com/jenkinsci/opentelemetry-plugin/blob/master/demos/config/otel-collector-config.yaml contains an example of configuring the OTEL collector against different vendors for metrics logs and traces, if it helps 

Otherwise, i'd suggest to go to the official OTEL docs as there might be some considerations to take into accoint, such as the version of the collector and the vendors you might use.

**Comment by v1v** [comment]
No further feedback, so closing this now
