### ISSUE TITLE
Opentelemetry plugin missing fields in elastic APM

### ISSUE THREAD

**Issue by Neelam-zanvar** [jenkinsci/opentelemetry-plugin#543]
I have installed opentelemetry plugin in jenkins and want to visualise the metrics on elastic apm. I am able to view maximum data on jenkins dashboard on elastic observability however some fields are missing. Here are my configurations
![image](https://user-images.githubusercontent.com/98389856/197178873-50f8a823-c095-4607-9fa2-94b6a23f9c85.png)
![image](https://user-images.githubusercontent.com/98389856/197178922-b8b2165b-3f6c-4c86-890c-32c7c58ccd9d.png)
![image](https://user-images.githubusercontent.com/98389856/197179034-23a97a5d-e1ab-4564-8ae0-43de4a895c5b.png)
![image](https://user-images.githubusercontent.com/98389856/197179309-ae061132-524a-4ae3-95a8-c307a4cfae87.png)
![image](https://user-images.githubusercontent.com/98389856/197179386-617b106c-37e4-47da-89b4-63f8e9f3b581.png)
I have imported jenkins dashboard on kibana.
installed apm server. When i click on elastic observability on jenkins page few metrics are missing

![image](https://user-images.githubusercontent.com/98389856/197179559-6e073c63-1a20-4682-a81f-23c0cd31d4f1.png)
![image](https://user-images.githubusercontent.com/98389856/197179679-2eaf940a-0287-46e7-8c0c-fa318a1485da.png)
on jenkins log getting this 
![image](https://user-images.githubusercontent.com/98389856/197179791-6c32f7ff-4ee4-4212-ae1f-1372c734cd8c.png)
while configuring the otel plugin it was mentioned that the user needs to have read access to logs-apm.app index template. how can i verify the same?

**Comment by v1v** [comment]
Duplicates https://github.com/jenkinsci/opentelemetry-plugin/issues/536

Metrics are not related to the logs credentials. IIUC, you mentioned in some previos issues that the APM server was configured without authentication.

On the other hand, in order to be more efficient, it is recommended to go through the existing open issues and see if there is any already reported, additionally, there is a template issue in this project to help with versions, configurations, by skipping this will make things harder

I'll close this as duplicated
