### ISSUE TITLE
Allow to chose longer time range on grafana/tempo

### ISSUE THREAD

**Issue by taowang88** [jenkinsci/opentelemetry-plugin#844]
### What feature do you want to see added?

I am using this plugin with tempo as data source. Currently on jenkin job, when I click on the grafana OpenTelemetry link, 20 minuites time range is created/assigned as default on grafana.

I would like to have a feature that I can chose time range, i.e. 7 days so that I can find old trace data.

**Comment by cyrille-leclerc** [comment]
Hello @taowang88 , thanks for using the Jenkins OpenTelemetry Plugin.
Can you please clarify?
Can you confirm that you are referring to the URL "View pipeline in Grafana" (screenshot below)?
If so, the current time window spans from 10 mins before the build started to 10 mins after the
build ended.
Why do you need to expand this time window? Is it because you are chaining pipeline builds and lack of the big picture?

<img width="1146" alt="image" src="https://github.com/jenkinsci/opentelemetry-plugin/assets/459691/513f73ae-f647-4841-b464-924d64a37cbc">
